# Generated by Django 5.0.3 on 2024-08-08 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(blank=True, choices=[('calm', 'Спокойная'), ('happy', 'Радостная'), ('energetic', 'Энергичная'), ('playful', 'Игривая'), ('mood_swings', 'Перепады настроения'), ('irritated', 'Раздраженная'), ('sad', 'Грустная'), ('anxious', 'Встревоженная'), ('depressed', 'Подавлена'), ('guilty', 'Чувство вины'), ('obsessive_thoughts', 'Навязчивые мысли'), ('low_energy', 'Мало энергии'), ('apathetic', 'Апатичная'), ('confused', 'Растерянная'), ('self_critical', 'Жесткая самокритика')], max_length=30, null=True)),
                ('symptom_name', models.CharField(blank=True, choices=[('all_ok', 'Все в порядке'), ('lower_abdominal_pain', 'Боли внизу живота'), ('sensitive_breasts', 'Чувствительная грудь'), ('headache', 'Головная боль'), ('acne', 'Прыщи'), ('back_pain', 'Боль в спине'), ('fatigue', 'Усталость'), ('increased_appetite', 'Повышенный аппетит'), ('insomnia', 'Бессонница'), ('abdominal_pain', 'Боль в животе'), ('vaginal_dryness', 'Сухость во влагалище')], max_length=30, null=True)),
                ('discharge', models.CharField(blank=True, choices=[('none', 'Выделений нет'), ('creamy', 'Кремообразные'), ('watery', 'Водянистые'), ('sticky', 'Липкие'), ('mucous', 'Слизистые'), ('spotting', 'Кровомажущие'), ('atypical', 'Нетипичные')], max_length=30, null=True)),
                ('digestion', models.CharField(blank=True, choices=[('nausea', 'Тошнота'), ('bloating', 'Вздутие живота'), ('constipation', 'Запор'), ('diarrhea', 'Диарея')], max_length=30, null=True)),
                ('other', models.CharField(blank=True, choices=[('travel', 'Путешествие'), ('stress', 'Стресс'), ('meditation', 'Медитация'), ('journaling', 'Ведение дневника'), ('kegel_exercises', 'Упражнения Кегеля'), ('breathing_exercises', 'Дыхательные упражнения'), ('illness_or_injury', 'Болезнь или травма'), ('alcohol', 'Алкоголь')], max_length=30, null=True)),
                ('physical_activity', models.CharField(blank=True, choices=[('none', 'Тренировки не было'), ('yoga', 'Йога'), ('gym', 'Тренажерный зал'), ('aerobics_and_dance', 'Аэробика и танцы'), ('swimming', 'Плавание'), ('team_sport', 'Командный спорт'), ('running', 'Бег'), ('cycling', 'Велосипед'), ('walking', 'Ходьба')], max_length=30, null=True)),
                ('water', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenstrualDayStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('periods', 'Periods.'), ('ordinary_day', 'Ordinary Day.'), ('ovulation', 'Ovulation.'), ('period_may_start', 'Maybe your period will start today.'), ('delay_of_menstruation', 'Delay of menstruation.')], default='ordinary_day', max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('symptoms', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='www.symptom')),
            ],
        ),
    ]
